# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  webapidemo:
    image: webapidemo
    build:
      context: .
      dockerfile: WebApiDemo/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5286:5286
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
