# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  blazorbbsdemo80:
    image: blazorbbsdemo80
    build:
      context: .
      dockerfile: BlazorBBSDemo8.0/Dockerfile
    ports:
      - 5250:5250
